# Pre-commit hooks for Simple RAG project
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Ruff - Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  # basedpyright - Type checking (using local system hook)
  # Only show errors, ignore warnings
  - repo: local
    hooks:
      - id: basedpyright
        name: basedpyright
        entry: uv run basedpyright --level=ERROR
        language: system
        types: [python]
        pass_filenames: false

  # Basic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check for debugger imports and breakpoints in Python source
      - id: debug-statements
      # Check for large files added to git
      - id: check-added-large-files
        args: ['--maxkb=1000']
      # Trim trailing whitespace
      - id: trailing-whitespace
      # Check JSON syntax
      - id: check-json
      # Check YAML syntax
      - id: check-yaml
        args: ['--unsafe']
      # Check TOML syntax
      - id: check-toml

  # Security checks (excluding common false positives for development projects)
  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.0'
    hooks:
      - id: bandit
        args: ['-r', '--skip', 'B101,B104,B110,B601,B608']
        exclude: ^tests/

# Configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
